# build this: e.g docker build -t broker .
# to run this container, do:
# on the host:
# make sure you're in the X environment
# xhost +
# docker run --rm -ti --privileged -e DISPLAY -v /tmp:/tmp --network dream_catcher --name broker broker

#FROM ubuntu
FROM python:3.7.5-alpine3.10

RUN apk add --update --no-cache \
	--virtual=.build-dependencies \
	python3-dev \
	py-setuptools g++ && \
	apk add --no-cache --update git cmake unzip wget mosquitto-clients && \
	ln -s /usr/include/locale.h /usr/include/xlocale.h && \
	pip install paho-mqtt numpy cython pandas gdal folium geopy ibm-cos-sdk osmnx && \
	apk del .build-dependencies
	

WORKDIR /
COPY broker.py /usr/src/app/
COPY gps_simulator.py /usr/src/app/
COPY gps_logs.csv /usr/src/app/

CMD ["python","/usr/src/app/broker.py"]
